#!/bin/bash

echo "=== Désinstallation d'Apache ==="
sudo apt purge apache2 -y

echo "=== Installation et activation de NGINX ==="
sudo apt update && sudo apt install nginx -y
sudo systemctl enable nginx
sudo systemctl start nginx

echo "=== Configuration de la page de la DMZ ==="
echo "<h1>Bienvenue sur le serveur DMZ de Enzo (Version Automatisee)</h1>" | sudo tee /var/www/html/index.html

echo "=== Déploiement terminé avec succès ! ==="
